language: cpp
dist: bionic

matrix:
    include:
        # Ubuntu Linux 18.04 gcc7.1
        - os: linux
          compiler: gcc
          before_install:
              - export CXX="g++-7" CC="gcc-7"
              - export BUILD="make"

        # Apple OSX LLVM version 10.0.0 (clang-1000.11.45.5)
        - os: osx
          osx_image: xcode10.2
          compiler: clang

        # OSX gcc7
        - os: osx
          osx_image: xcode10.2
          compiler: gcc
          before_install:
              - rm -rf /usr/local/include/c++
              - brew update
              - brew install gcc@7
              - export CXX="g++-7" CC="gcc-7"
              - export BUILD="make"
              - sudo softwareupdate -i "Command Line Tools (macOS Mojave version 10.14) for Xcode-10.2"

        # Windows VS 2017
        - os: windows
          compiler: dotnet
          before_install:
              - export CXX="dotnet" CC="dotnet"
              - export BUILD="dotnet build synthewareQ.sln"

notifications:
  email: false

script:
  - $CXX --version
  
  # Build the examples
  - mkdir build
  - cd build
  - cmake .. -DCMAKE_BUILD_TYPE=Debug && $BUILD
