language: cpp
dist: xenial

matrix:
    include:
        # Ubuntu Linux 16.04 gcc7.1
        - os: linux
          compiler: gcc
          before_install:
              export CXX="g++-7" CC="gcc-7"

        # Apple OSX LLVM version 10.0.0 (clang-1000.11.45.5)
        - os: osx
          osx_image: xcode10.1
          compiler: clang

        # OSX gcc7
        - os: osx
          osx_image: xcode10.1
          compiler: gcc
          before_install:
              - rm -rf /usr/local/include/c++
              - brew update
              - brew install gcc6
              - export CXX="g++-7" CC="gcc-7"
              - sudo softwareupdate -i "Command Line Tools (macOS High Sierra version 10.13) for Xcode-10.1"

notifications:
  email: false

script:
  - $CXX --version
  
  # Build the examples
  - mkdir build
  - cd build
  - cmake .. -DCMAKE_BUILD_TYPE=Debug && make -j4
